service: delete-product
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  deleteProduct:
    handler: index.handler
    events:
      - http:
          path: product/{id}
          method: delete
